# Builds the docs and deploys them to GitHub pages.
name: Build and deploy to Github Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

# Workflow run composed of build and deploy jobs
jobs:

  # Builds and uploads artifact for GitHib pages
  build_and_deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks out git repository
      - uses: actions/checkout@v4

      # Builds tools and generates md docs under ./site
      # - The BASE_URL env variable sets the baseurl for the Jekyll configuration
      - name: Build tools and generate md docs
        run: |
          git submodule init
          git submodule update
          repo_name="$(echo ${{ github.repository }} | cut -d'/' -f2)"
          export BASE_URL=${repo_name}/${{ github.ref_name }}
          ./tools/build.sh

      # Builds static html web pages with jekyll under ./site
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - name: Install bundler and gems for jekyll
        run: |
          cd site
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Build static html web page with jekyll
        run: |
          cd site
          ls Gemfile
          bundle exec jekyll build

      # Deploys to branch subdirectory
      - name: Deploy to gh-pages/${{ github.ref_name }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/_site
          destination_dir: ${{ github.ref_name }}

